// This file was generated by img2gb, DO NOT EDIT

#ifndef _DEATH_TILEMAP_H
#define _DEATH_TILEMAP_H

extern const UINT8 DEATH_TILEMAP[];
#define DEATH_TILEMAP_WIDTH 20
#define DEATH_TILEMAP_HEIGHT 12


#endif
