// This file was generated by img2gb, DO NOT EDIT

#ifndef _DEFEAT_TILEMAP_H
#define _DEFEAT_TILEMAP_H

extern const UINT8 DEFEAT_TILEMAP[];
#define DEFEAT_TILEMAP_WIDTH 20
#define DEFEAT_TILEMAP_HEIGHT 12


#endif
