// This file was generated by img2gb, DO NOT EDIT

#ifndef _VICTORY_TILEMAP_H
#define _VICTORY_TILEMAP_H

extern const UINT8 VICTORY_TILEMAP[];
#define VICTORY_TILEMAP_WIDTH 20
#define VICTORY_TILEMAP_HEIGHT 12


#endif
